### ISSUE TITLE
BOT_ID missing from env

### ISSUE THREAD

**Issue by shadowbq** [scottbrumley/opendxl-slack#2]
The README does not describe the use of the BOT_ID env 

version 0.9.1 Release

```bash
BOT_ID is missing from ENV
```

**Comment by shadowbq** [comment]
https://github.com/scottbrumley/opendxl-slack/blob/997ae29b12ad0beb82f77244f62026ca1db089f6/tie_service.py#L178

**Comment by shadowbq** [comment]
botname is the username. The error doesn't map correctly, and makes it seem like you should of included the BOT_ID

**Comment by scottbrumley** [comment]
Thanks for the feedback.  Yeah I caught that a few weeks ago when we were doing a code review, so I'm confused that is not all consistently BOT_NAME.  The BOT_NAME is the BOT_ID and it maps to the name of the bot when you setup the bot in slack.
